LINK_MAIN_PAGE = 'http://selenium1py.pythonanywhere.com'
LINK_CATALOGUE_PAGE = 'http://selenium1py.pythonanywhere.com/catalogue'
LINK_PRODUCT_PAGE = 'http://selenium1py.pythonanywhere.com/catalogue/the-shellcoders-handbook_209/'
LINK_PRODUCT_PAGE_PROMO = 'http://selenium1py.pythonanywhere.com/catalogue/coders-at-work_207/?promo=offer0'
LINK_LOGIN_PAGE = 'http://selenium1py.pythonanywhere.com/accounts/login'
LINK_BASCET_CASE = 'http://selenium1py.pythonanywhere.com/ru/basket'
